Repository UCR-Solar-Car/DriverInterface, pull requests merged in 2022-08, with the labels that each got.

#71 Added rules and regulations for quick access
  README.md
Labels: HIGH, HEAVYWORK

#91 Scaling icons
  DriverInterface.pro
  battery.cpp
  cruise.cpp
  distance.cpp
  gears.cpp
  horn.cpp
  indicators.cpp
  lights.cpp
  scaler.cpp
  scaler.h
  speed.cpp
  warnings.cpp
Labels: DO NOT MERGE

#129 Scale Icons
  DriverInterface.pro
  battery.cpp
  battery.h
  distance.cpp
  gears.cpp
  gears.h
  global_variables.h
  horn.cpp
  horn.h
  indicators.cpp
  indicators.h
  lights.cpp
  lights.h
  main.cpp
  mainwindow.cpp
  mainwindow.ui
  motor.cpp
  motor.h
  speed.cpp
  states.h
  tirepressure.cpp
  tirepressure.h
Labels: DO NOT MERGE

#130 tirePressureIndicators
  mainwindow.cpp
  tirepressure.cpp
  tirepressure.h
Labels: READY FOR REVIEW

#132 Lights Cleanup
  lights.cpp
  tirepressure.cpp
Labels: READY FOR REVIEW

#133 Jyro88/speed clean up
  speed.cpp
Labels: READY FOR REVIEW

#134 Shrinking data types - Distance Class
  distance.cpp
  distance.h
Labels: READY FOR REVIEW

#135 Shrinking data types - Battery Class
  battery.cpp
  battery.h
Labels: READY FOR REVIEW

#136 Shrinking data types - Gears
  gears.cpp
  gears.h
Labels: READY FOR REVIEW

#137 Shrinking data types - Indicators
  indicators.cpp
  indicators.h
Labels: READY FOR REVIEW

#139 Update indicators.cpp
  indicators.cpp
Labels: READY FOR REVIEW

#138 Update mainwindow.cpp
  mainwindow.cpp
Labels: READY FOR REVIEW

#140 Reducing Memory Size - Horn Class
  horn.cpp
  horn.h
Labels: READY FOR REVIEW

#141 Reducing data sizes - Lights Class
  lights.cpp
  lights.h
Labels: READY FOR REVIEW

#142 Reduce data sizes - Motor Class
  motor.cpp
  motor.h
Labels: READY FOR REVIEW

#143 Reduced data sizes - Motor Class
  speed.cpp
  speed.h
Labels: READY FOR REVIEW

#144 Update distance.cpp
  distance.cpp
Labels: READY FOR REVIEW

#145 Update battery.cpp
  battery.cpp
Labels: READY FOR REVIEW

#160 delete scalar class
  DriverInterface.pro
  battery.cpp
  distance.cpp
  gears.cpp
  horn.cpp
  indicators.cpp
  lights.cpp
  motor.cpp
  scaler.cpp
  scaler.h
  tirepressure.cpp
Labels: READY FOR REVIEW

#147 Reduce data sizes - Tire Pressure Class
  tirepressure.cpp
  tirepressure.h
Labels: READY FOR REVIEW

#162 Jyro88/tire pressure safety precautions
  mainwindow.cpp
  tirepressure.cpp
  tirepressure.h
Labels: READY FOR REVIEW

#146 Updating Main
  .gitignore
  DriverInterface.pro
  background.cpp
  background.h
  battery.cpp
  battery.h
  car.png
  cruise.cpp
  cruise.h
  cruise.png
  distance.cpp
  distance.h
  drive.png
  gears.cpp
  gears.h
  global_variables.h
  horn.cpp
  horn.h
  icons.qrc
  indicators.cpp
  indicators.h
  lights.cpp
  lights.h
  logo.png
  low-battery.png
  main.cpp
  mainwindow.cpp
  mainwindow.h
  mainwindow.ui
  motor.cpp
  motor.h
  neutral.png
  parking.png
  reverse.png
  speed.cpp
  speed.h
  states.h
  tirepressure.cpp
  tirepressure.h
  warnings.cpp
  warnings.h
Labels: HIGH, READY FOR REVIEW

#163 Memory reduction
  mainwindow.cpp
  mainwindow.h
Labels: READY FOR REVIEW

#164 Reducing access of Lights class
  lights.cpp
  lights.h
  mainwindow.cpp
Labels: READY FOR REVIEW

#165 Reduced access of indicators class
  indicators.cpp
  indicators.h
  mainwindow.cpp
Labels: READY FOR REVIEW

#166 Reduced horn class access
  horn.cpp
  horn.h
  mainwindow.cpp
Labels: READY FOR REVIEW

#167 Reduced Gears class access
  gears.cpp
  gears.h
  mainwindow.cpp
Labels: READY FOR REVIEW

#169 reduce distance class access
  distance.cpp
  distance.h
  mainwindow.cpp
  mainwindow.ui
  speed.cpp
Labels: READY FOR REVIEW

#168 Reduced total function calls
  background.cpp
  battery.cpp
  gears.cpp
  mainwindow.cpp
Labels: READY FOR REVIEW

#170 Reduce Speed Access
  mainwindow.cpp
  speed.cpp
  speed.h
Labels: READY FOR REVIEW

#171 Reduce Motor Access
  motor.cpp
  motor.h
Labels: READY FOR REVIEW
